services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mentor'
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - 3307:3306
